/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.saojudas.sistemalavanderia;

import com.saojudas.sistemalavanderia.Conexao.ConexaoBanco;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class TelaOrdemServicos extends javax.swing.JFrame {

    /**
     * Creates new form TelaServicos
     */
    public TelaOrdemServicos() {
        initComponents();
        setLocationRelativeTo(null);
        carregarOrdens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblRecebido = new javax.swing.JLabel();
        lblLavando = new javax.swing.JLabel();
        lblSecando = new javax.swing.JLabel();
        lblConcluido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRecebido = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listLavando = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listSecando = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listConcluido = new javax.swing.JList<>();
        btnAvancar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 650));
        setMinimumSize(new java.awt.Dimension(800, 650));
        setPreferredSize(new java.awt.Dimension(800, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblRecebido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRecebido.setText("Recebido");

        lblLavando.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLavando.setText("Lavando");

        lblSecando.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSecando.setText("Secando");

        lblConcluido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConcluido.setText("Concluído");

        listRecebido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listRecebido);

        listLavando.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listLavando);

        listSecando.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listSecando);

        listConcluido.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listConcluido);

        btnAvancar.setText(">> Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        btnVoltar.setText("<< Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("🔄 Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo (Personalizado) (1).png"))); // NOI18N

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu (Personalizado).png"))); // NOI18N
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenu)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblMenu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRecebido)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLavando))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(lblSecando)
                        .addGap(124, 124, 124)
                        .addComponent(lblConcluido)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvancar)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar)
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecebido)
                    .addComponent(lblLavando)
                    .addComponent(lblSecando)
                    .addComponent(lblConcluido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvancar)
                    .addComponent(btnVoltar)
                    .addComponent(btnAtualizar))
                .addGap(41, 41, 41)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        ConexaoBanco.getConexao();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        btnAvancar.addActionListener(e -> avancarStatus());
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        btnVoltar.addActionListener(e -> voltarStatus());
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        dispose();
        new TelaMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_lblMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOrdemServicos().setVisible(true);
            }
        });
    }
    
    private void carregarOrdens() {
        DefaultListModel<String> modeloRecebido = new DefaultListModel<>();
        DefaultListModel<String> modeloLavando = new DefaultListModel<>();
        DefaultListModel<String> modeloSecando = new DefaultListModel<>();
        DefaultListModel<String> modeloConcluido = new DefaultListModel<>();

        try {
            String sql = "SELECT os.id, SUBSTRING_INDEX(c.nome, ' ', 1) as nome, os.data_criacao, os.status, s.nome as servico " +
                         "FROM ordens_servico os " +
                         "JOIN clientes c ON os.id_cliente = c.id " +
                         "JOIN servicos s ON os.id_servico = s.id";
            PreparedStatement ps = ConexaoBanco.getConexao().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String nome = rs.getString("nome");
                String servico = rs.getString("servico");
                Date data = rs.getDate("data_criacao");
                String status = rs.getString("status");
                String item = id + " - " + nome + " - " + servico;

                switch (status) {
                    case "Recebido": modeloRecebido.addElement(item); break;
                    case "Lavando": modeloLavando.addElement(item); break;
                    case "Secando": modeloSecando.addElement(item); break;
                    case "Concluído": modeloConcluido.addElement(item); break;
                }
            }

            listRecebido.setModel(modeloRecebido);
            listLavando.setModel(modeloLavando);
            listSecando.setModel(modeloSecando);
            listConcluido.setModel(modeloConcluido);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar ordens: " + e.getMessage());
        }
    }

    private void avancarStatus() {
        javax.swing.JList<String> listaSelecionada = null;
        String statusAtual = null;
        String novoStatus = null;

        // Verifica qual lista tem um item selecionado
        if (!listRecebido.isSelectionEmpty()) {
            listaSelecionada = listRecebido;
            statusAtual = "Recebido";
            novoStatus = "Lavando";
        } else if (!listLavando.isSelectionEmpty()) {
            listaSelecionada = listLavando;
            statusAtual = "Lavando";
            novoStatus = "Secando";
        } else if (!listSecando.isSelectionEmpty()) {
            listaSelecionada = listSecando;
            statusAtual = "Secando";
            novoStatus = "Concluído";
        } else if (!listConcluido.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "Ordem já está concluída!");
            return;
        }

        moverOrdem(listaSelecionada, novoStatus);
    }

    private void voltarStatus() {
        javax.swing.JList<String> listaSelecionada = null;
        String statusAtual = null;
        String novoStatus = null;

        // Verifica qual lista tem um item selecionado
        if (!listConcluido.isSelectionEmpty()) {
            listaSelecionada = listConcluido;
            statusAtual = "Concluído";
            novoStatus = "Secando";
        } else if (!listSecando.isSelectionEmpty()) {
            listaSelecionada = listSecando;
            statusAtual = "Secando";
            novoStatus = "Lavando";
        } else if (!listLavando.isSelectionEmpty()) {
            listaSelecionada = listLavando;
            statusAtual = "Lavando";
            novoStatus = "Recebido";
        } else if (!listRecebido.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "Ordem já está no status inicial!");
            return;
        }

        moverOrdem(listaSelecionada, novoStatus);
    }

    private void moverOrdem(javax.swing.JList<String> lista, String novoStatus) {
        String selecionado = lista.getSelectedValue();
        if (selecionado != null && !selecionado.isEmpty()) {
            try {
                int id = Integer.parseInt(selecionado.split(" - ")[0]);

                String sql = "UPDATE ordens_servico SET status = ? WHERE id = ?";
                PreparedStatement ps = ConexaoBanco.getConexao().prepareStatement(sql);
                ps.setString(1, novoStatus);
                ps.setInt(2, id);
                ps.executeUpdate();

                carregarOrdens(); // Recarrega as listas
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar status: " + e.getMessage());
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblConcluido;
    private javax.swing.JLabel lblLavando;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblRecebido;
    private javax.swing.JLabel lblSecando;
    private javax.swing.JList<String> listConcluido;
    private javax.swing.JList<String> listLavando;
    private javax.swing.JList<String> listRecebido;
    private javax.swing.JList<String> listSecando;
    // End of variables declaration//GEN-END:variables
}
